language: ruby

rvm:
  - 2.2
env:
  - DB=postgres

before_script:
  - "cp config/database.ci.yml config/database.yml"
  - "RAILS_ENV=test bundle exec rake --trace db:migrate test"

script: "RAILS_ENV=test bundle exec rake spec"
