language: ruby

rvm:
  - 2.2

env:
  - DB=postgres

before_script:
  - "cp config/database.ci.yml config/database.yml"
  - "cp config/settings.teatro.yml config/settings.yml"
  - "RAILS_ENV=test bundle exec rake db:create"

script: "RAILS_ENV=test bundle exec rake spec"
