# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: 4d08bef94cb83e8c3d10a56e41783b1b681e5a21a13b17c4b8165f719cccc521540ee2331cd79bda53ecb4e2e0c6174c6eb065eaeef9f8a04994fb07f331c9a5
  github_key: 5dc5ba33b9dc14101227
  github_secret: 99115f4606913c1f58e808621e6a5ade29cbd3c4
  amazon_key: AKIAJFNQJAMBDTISKN7Q
  amazon_secret: 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

test:
  secret_key_base: 99a038a0eae76dfb77c050b63267c3814b004a5041773488e1f1a0d63a8293cffbf2a8764c540244f0a118363572556a6976660bf80e3e8fd3ca0cb76a22857a
  github_key: 5dc5ba33b9dc14101227
  github_secret: 99115f4606913c1f58e808621e6a5ade29cbd3c4
  amazon_key: AKIAJFNQJAMBDTISKN7Q
  amazon_secret: 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

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
  amazon_key: <%= ENV["AMAZON_KEY"] %>
  amazon_secret: <%= ENV["AMAZON_SECRET"] %>
